export const SIDE_MENU_ITEMS_LOADED = "SIDE_MENU_ITEMS_LOADED";

export const GET_FIRST_DATA = "GET_FIRST_DATA";
export const FIRST_DATA_LOADED = "FIRST_DATA_LOADED";

export const GET_SECOND_DATA = "GET_SECOND_DATA";

export const GET_THIRD_DATA = "GET_THIRD_DATA";