export const SIDE_MENU_ITEMS_LOADED = "SIDE_MENU_ITEMS_LOADED";

export const GET_FIRST_DATA = "GET_FIRST_DATA";
export const FIRST_DATA_LOADED = "FIRST_DATA_LOADED";
export const SET_FISR_IS_ARCHIVED = "SET_FISR_IS_ARCHIVED";
export const ADD_REMOVE_FIRST_FILTER_COLOR = "ADD_REMOVE_FIRST_FILTER_COLOR";
export const SET_FIRST_FILTER_ARCHIVE = "SET_FIRST_FILTER_ARCHIVE";
export const SET_FIRST_FILTER_TEXT = "SET_FIRST_FILTER_TEXT";

export const GET_SECOND_DATA = "GET_SECOND_DATA";

export const GET_THIRD_DATA = "GET_THIRD_DATA";